name: Post to X

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 3  * * *'
    - cron: '0 10 * * *'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install playwright pytz python-dotenv
          playwright install chromium

      - name: Run poster script
        env:
          X_EMAIL: ${{ secrets.X_EMAIL }}
          X_PASSWORD: ${{ secrets.X_PASSWORD }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: python scripts/poster.py
